### ISSUE TITLE
Consistency and Forum

### ISSUE THREAD

**Issue by 8rax** [maxpumperla/deep_learning_and_the_game_of_go#78]
Hello, 

I will raise a few issues that I had so far going through the book. It is not biggie and not really blocking at the moment but still a little bit annoying. 

 First, It is advertised in the book that there is a private forum on manning. I am quoting : 

_Book forum
Purchase of Deep Learning and the Game of Go includes free access to a private web forum run by Manning Publications, where you can make comments about the book, ask technical questions, and receive help from the author and from other users. To access the forum, go to https://forums.manning.com/forums/deep-learning-and-the-game-of-go. You can also learn more about Manning’s forums and the rules of conduct at https://forums.manning.com/forums/about._

Where is this forum to discuss about the content of the book ? Because when I follow the link I have a digital version of the book, not a forum for discussions. 

In addition, I am finishing chapter 3 and I am experiencing issues concerning the consistency of the code. When you launch you first bot vs bot on page 45, the import provided in the sample code is "import goboard", you have a goboard_slow at that point not a goboard, the import fails (alright, not the end of the world but still). 

It's worse after that, if you get the code from the Chapter 3 branch here on github, it contains code that was not even touched in chapter 3 like the scoring, making the whole process of reconciliating what is in the book and what is on github very tedious. This does not offer the right step by step approach, I am already focusing more on sorting out what should be in the code or not than actually trying to understand it. 

Do I do something wrong ? Is there something I missed ? It would be very helpful if it was posssible to follow the code in the book and then have a step by step incremental version on github, is this possible to find ?

**Comment by maxpumperla** [comment]
Hi @8rax, I'm glad it's not a major annoyance and not blocking you, but sorry to hear you're disappointed by so many things. I sincerely hope you get something out of the book still.

Book forum: In the link above there is a discussion section ("forum") that you can access by hitting "Discuss" on the right. I hope you can find it. P.s.: we're not maintaining Manning sites, for other questions about navigating their site you should contact them, please.

Import: yes, you are right about that and it's our mistake we didn't catch this before the book went into print. Not much we can do about this, since we either have to keep things as they are or introduce breaking changes (both aren't ideal). In your case you can simply do `from dlgo import goboard_slow as goboard`. Let me go through chapter 3 branch to see if I can quickly fix this.

Scoring etc.: It would be very helpful if you could provide us with a list of all the inconveniences you found. Apart from scoring, what else is too much there?

Best wishes,
Max

**Comment by maxpumperla** [comment]
@8rax I fixed the inconsistencies in the `chapter_3` branch, meaning that I adapted the imports (which now deviate from the book) and I deleted the code that has not been introduced at that point. hope that helps!
